### ISSUE TITLE
Consistent exception hierarchy

### ISSUE THREAD

**Issue by jasonab** [Yubico/java-u2flib-server#34] opened 2017-12-21 01:15 UTC
It would be easier to manage the exceptions from the library if they all descended from a common ancestor. Right now, I have to catch multiple different exceptions in my catch blocks, which leads to ugly code.

**Comment by emlun** [comment] 2017-12-21 12:51
Thanks for the suggestion! That sounds reasonable, we can probably make that happen.

**Comment by emlun** [comment] 2018-01-09 16:16
Looking at this again, I feel like there might be little point in introducing a common ancestor exception since the exceptions are used to signal mostly separate failure conditions:

- `U2fBadConfigurationException` means there's something wrong in the server configuration.
- `U2fBadInputException` means the client's response is malformed.
- `NoEligibleDevicesException` means the state of the client's account does not permit initiating an authentication operation, because no devices are registered.
- `DeviceCompromisedException` and `InvalidDeviceCounterException` mean the signature counter returned from the client is or has been invalid.

Can you share one or a few specific examples of ugly code caused by the current exception (non-)hierarchy? That would help decide how we want to go about this.

**Comment by jasonab** [comment] 2018-01-09 18:07
Sure, let's look at these from my implementor's perspective:

- U2fBadConfigurationException is absolutely a runtime exception, and there's no reason for any client code to catch it.
- U2fBadInputException is a runtime exception from you, but it's a checked exception to me. I'm sending you user input that could be anything, and it could fail for any reason. I understand that this is supposed to be coming from the key, but I can't guarantee that, so I have to handle this exception to avoid a 500.
- NoEligibleDevicesException is properly a checked exception that I have to handle.
- DeviceCompromisedException is properly a checked exception.

For me, any of the final 3 could be thrown during an authentication flow, and if any of them are thrown, it means authentication failed. I agree that I might need to message them differently, but with the separate types, I have to have multiple catch blocks to differentiate the cause of the error. What would be easier for me is to be able to catch a single "u2f process failed" type exception, with an embedded error code that explains why.

Right now, I have to catch U2fBadInputException and DeviceCompromised exception separately in the same flow, but react the same way.

**Comment by emlun** [comment] 2018-01-15 14:32
Ah yes, I see. I guess my dabbling in Scala had me still thinking in expression-oriented terms rather than Java's statement-oriented paradigm.

**Comment by emlun** [comment] 2018-01-16 08:57
This is now released in version 0.19.0. Please have a look, and let us know if you have any more suggestions for improvements. Thanks!

**Closed by emlun** 2018-01-16 08:57 UTC
Labels: enhancement
